"""Compare selected historical source/key controls on two recorded CPU runtimes."""
import ast,base64,hashlib,json,pathlib
R=pathlib.Path(__file__).resolve().parents[1];A=R/'analysis';D=R/'sources/historical_key_2026_10_08';H=R/'sources/run_code_2026_10_08';checks=[]
def check(n,v):assert v,n;checks.append({'name':n,'passed':True})
a=json.loads((A/'historical_key_pipeline_jax_0_11_0.json').read_text());b=json.loads((A/'historical_key_pipeline_jax_0_7_2.json').read_text());bindings=[];manifests={r:json.loads((H/(r+'_code_manifest.json')).read_text())['contents'] for r in ['producer','continuation']}
acq=json.loads((A/'historical_key_acquisition_v123.json').read_text())['records']
for rec in acq:
 if 'artifact_path' not in rec:continue
 p=R/'sources'/rec['file'];blob=p.read_bytes();key=rec['artifact_path'];md5=base64.b64encode(hashlib.md5(blob).digest()).decode();bindings.append({'file':str(p.relative_to(R)),'artifact_path':key,'matches_both_run_manifests':all(m[key]['digest']==md5 and m[key]['size']==len(blob) for m in manifests.values())})
check('Six selected historical source payloads match both independent run manifests',len(bindings)==6 and all(x['matches_both_run_manifests'] for x in bindings))
reqs={r:dict(line.split('==',1) for line in (D/(r+'_requirements.txt')).read_text().splitlines() if '==' in line) for r in manifests};version=ast.parse((D/'jax_version.py').read_text());release=next(n.value.value for n in version.body if isinstance(n,ast.AnnAssign) and getattr(n.target,'id','')=='_release_version')
check('Both dependency records and uploaded JAX version declare0.11.0 with numpy2.3.5',release=='0.11.0' and all(d['jax']==d['jaxlib']=='0.11.0' and d['numpy']=='2.3.5' for d in reqs.values()) and a['runtime']['jax']==a['runtime']['jaxlib']=='0.11.0' and a['runtime']['numpy']=='2.3.5')
check('Both runtime probes bind current script/source bytes and nine scoped controls',all(v['checks_passed']==len(v['checks'])==9 and all(c['passed'] for c in v['checks']) and all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in v['source_sha256'].items()) for v in [a,b]))
check('Eight variants all child keys and mixed-block prefixes match between0.11.0 and0.7.2',len(a['variants'])==8 and a['variants']==b['variants'] and (A/'historical_child_keys_jax_0_11_0.csv').read_bytes()==(A/'historical_child_keys_jax_0_7_2.csv').read_bytes())
check('Source-derived-key two-declaration boundary controls agree across selected versions',a['boundary_with_declared_derived_key']==b['boundary_with_declared_derived_key'] and a['boundary_with_declared_derived_key']['hybrid_block_repeated_logical_ids']==5346)
base=a['variants']['partitionable=True,seed=0,data_seed=None'];explicit=a['variants']['partitionable=True,seed=0,data_seed=0'];off=a['variants']['partitionable=False,seed=0,data_seed=None']
summary={'declared_default':{k:base[k] for k in ['data_key','mix_key','shuffle_key']},'explicit_data_seed_zero':{k:explicit[k] for k in ['data_key','mix_key','shuffle_key']},'changed_child_keys_none_vs_zero':sum(base['child_keys'][n]!=explicit['child_keys'][n] for n in base['child_keys']),'changed_child_keys_partitionable_true_vs_false':sum(base['child_keys'][n]!=off['child_keys'][n] for n in base['child_keys']),'boundary_with_declared_derived_key':a['boundary_with_declared_derived_key']}
files=[pathlib.Path(__file__),A/'historical_key_pipeline_jax_0_11_0.json',A/'historical_key_pipeline_jax_0_7_2.json',A/'historical_child_keys_jax_0_11_0.csv',A/'historical_child_keys_jax_0_7_2.csv',A/'historical_key_acquisition_v123.json',H/'producer_code_manifest.json',H/'continuation_code_manifest.json']+list(D.iterdir())
out={'scope':__doc__,'checks_passed':len(checks),'checks':checks,'bindings':bindings,'runtime_comparison':{'first':a['runtime'],'second':b['runtime'],'selected_outputs_equal':True},'summary':summary,'source_sha256':{str(p.relative_to(R)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(set(files))},'scope_limit':'Selected seed/key/mixed-block controls on CPU only; not full environment equivalence or proof of actual historical key execution. Synthetic finite identities, no actual child shuffle/cache/simulation or token read.','restore_source_observation':{'file':'sources/historical_key_2026_10_08/train_ep.py','initialization_line':844,'restore_assignment_line':848,'status':'source_inspected_not_executed','implication':'Changed initialization key does not prove changed restored model parameters'},'actual_executed_historical_key':None,'actual_runtime_imports_verified':None,'actual_token_repetition_count':None,'actual_training_loss_effect':None,'actual_model_seed_variance_isolated':None}
(A/'historical_key_versions.json').write_text(json.dumps(out,indent=2)+'\n');print('Cross-runtime controls',len(checks));print(json.dumps(summary))
