"""Original AdamH transformation with explicit real-array NumPy moment/tree substitutes.
No Optax implementation, JAX compilation, distributed reduction or actual checkpoint restore.
"""
import ast,collections,hashlib,json,pathlib,types
import numpy as np
R=pathlib.Path(__file__).resolve().parents[1];P=R/'sources/adamh_2026_10_05/adamh.py';checks=[]
def tm(f,*trees,**kw):return {k:f(*(t[k] for t in trees)) for k in trees[0]}
def zeros(t,dtype=None):return tm(lambda x:None if x is None else np.zeros_like(x,dtype=dtype),t)
def moment(g,m,b,order):return tm(lambda a,z:None if a is None else b*z+(1-b)*a**order,g,m)
def correct(t,b,c):return tm(lambda x:None if x is None else x/(1-b**int(c)),t)
def cast(t,dtype):return tm(lambda x:None if x is None else np.asarray(x,dtype=dtype),t)
GT=collections.namedtuple('Transform','init update');State=collections.namedtuple('State','count mu nu');otu=types.SimpleNamespace(tree_zeros_like=zeros,tree_update_moment=moment,tree_update_moment_per_elem_norm=moment,tree_bias_correction=correct,tree_cast=cast)
env={'jnp':np,'jax':types.SimpleNamespace(dtypes=types.SimpleNamespace(canonicalize_dtype=lambda x:x),tree=types.SimpleNamespace(map=tm),tree_util=types.SimpleNamespace(tree_map=tm),vmap=lambda f:lambda p,u:np.stack([f(a,b) for a,b in zip(p,u)])),'optax':types.SimpleNamespace(GradientTransformation=GT,safe_increment=lambda c:np.int32(min(int(c)+1,np.iinfo(np.int32).max))),'otu':otu,'ScaleByAdamHState':State,'_pin_sharding':lambda x,p:x}
f=next(x for x in ast.parse(P.read_text()).body if isinstance(x,ast.FunctionDef) and x.name=='scale_by_adamh');future=ast.ImportFrom(module='__future__',names=[ast.alias(name='annotations')],level=0);exec(compile(ast.fix_missing_locations(ast.Module(body=[future,f],type_ignores=[])),str(P),'exec'),env)
def ck(n,v):assert v,n;checks.append(n)
def transform(eps=1e-8,mu_dtype=None):return env[f.name](.9,.95,eps,.1,mu_dtype)
p={'p':np.array([[2.,0.],[0.,1.]],dtype=np.float32)};g1={'p':np.array([[1.,4.],[2.,3.]],dtype=np.float32)};g2={'p':np.array([[-2.,.2],[3.,-1.]],dtype=np.float32)};a=transform();s0=a.init(p);ck('Original init count is int32 zero',int(s0.count)==0 and s0.count.dtype==np.int32);ck('Original init stores two zero moments',np.all(s0.mu['p']==0) and np.all(s0.nu['p']==0))
u1,s1=a.update(g1,s0,p);ck('First updated moments match independent EMA formulas',np.allclose(s1.mu['p'],.1*g1['p']) and np.allclose(s1.nu['p'],.05*g1['p']**2));ck('Bias correction uses incremented count',int(s1.count)==1);q1=p['p']+u1['p'];ck('First projected matrix retains norm with nonzero update',np.isclose(np.linalg.norm(q1),np.linalg.norm(p['p'])) and not np.allclose(q1,p['p']))
u2,s2=a.update(g2,s1,{'p':q1});m=.9*.1*g1['p']+.1*g2['p'];v=.95*.05*g1['p']**2+.05*g2['p']**2;ck('Second moments retain first gradient history',np.allclose(s2.mu['p'],m) and np.allclose(s2.nu['p'],v));direction=(m/(1-.9**2))/(np.sqrt(v/(1-.95**2))+1e-8);intermediate=q1-.1*direction*np.linalg.norm(q1)/np.linalg.norm(direction);ref=intermediate*np.linalg.norm(q1)/np.linalg.norm(intermediate);ck('Second update matches independently reconstructed direction and projection',np.allclose(q1+u2['p'],ref));ck('Output count advances to two',int(s2.count)==2)
# In-memory copied state, not a deserialized Optax checkpoint.
copy=State(s1.count.copy(),{'p':s1.mu['p'].copy()},{'p':s1.nu['p'].copy()});uc,sc=a.update(g2,copy,{'p':q1});ck('Copied synthetic state repeats same second update',np.array_equal(uc['p'],u2['p']) and np.array_equal(sc.nu['p'],s2.nu['p']))
ur,sr=a.update(g2,a.init({'p':q1}),{'p':q1});ck('Reset moments change output despite identical parameter gradient and norm',not np.allclose(ur['p'],u2['p']) and np.isclose(np.linalg.norm(q1+ur['p']),np.linalg.norm(q1+u2['p'])))
b=transform(0);base=s1;ut,_=b.update(g2,base,{'p':q1});uz,_=b.update(g2,base._replace(count=np.int32(0)),{'p':q1});ck('Count-only reset cancels from normalized direction at eps zero and fixed LR',np.allclose(ut['p'],uz['p']))
b=transform(.5);ut,_=b.update(g2,base,{'p':q1});uz,_=b.update(g2,base._replace(count=np.int32(0)),{'p':q1});ck('Artificial large epsilon breaks count-only cancellation',not np.allclose(ut['p'],uz['p']))
b=transform(mu_dtype=np.float16);us,ss=b.update(g1,b.init(p),p);ck('Requested moment dtype casts returned mu but not nu',ss.mu['p'].dtype==np.float16 and ss.nu['p'].dtype==np.float32)
# Current source applies a single vmap over leading dimension; inner dims jointly normalized.
p4={'p':np.array([[[[1.,0.],[0.,0.]],[[2.,0.],[0.,0.]]]],dtype=np.float32)};g4={'p':np.array([[[[0.,1.],[0.,0.]],[[0.,0.],[0.,0.]]]],dtype=np.float32)};b=transform();uu,_=b.update(g4,b.init(p4),p4);q4=p4['p']+uu['p'];ck('One leading vmap preserves joint 4D slice norm',np.isclose(np.linalg.norm(q4),np.linalg.norm(p4['p'])));ck('AdamH inner 4D matrix norms can change',not np.allclose(np.linalg.norm(q4,axis=(2,3)),np.linalg.norm(p4['p'],axis=(2,3))))
b=transform();masked={'p':None};um,sm=b.update(masked,b.init(masked),masked);ck('Masked None parameter remains None and count advances',um['p'] is None and int(sm.count)==1)
cls=next(x for x in ast.parse((R/'sources/optimizer_2026_10_05/optimizer.py').read_text()).body if isinstance(x,ast.ClassDef));build=next(x for x in cls.body if isinstance(x,ast.FunctionDef) and x.name=='build');call=next(x for x in ast.walk(build) if isinstance(x,ast.Call) and isinstance(x.func,ast.Name) and x.func.id=='adamh_transform_at');ck('AdamH branch receives learning_rate rather than adam_lr',isinstance(call.args[0],ast.Name) and call.args[0].id=='learning_rate')
angle=lambda x,y:float(np.degrees(np.arccos(np.clip(np.vdot(x,y)/(np.linalg.norm(x)*np.linalg.norm(y)),-1,1))))
out={'checks_passed':len(checks),'checks':checks,'source_sha256':hashlib.sha256(P.read_bytes()).hexdigest(),'scope':__doc__,'artificial_learning_rate':.1,'second_step_with_moments':(q1+u2['p']).tolist(),'second_step_reset_moments':(q1+ur['p']).tolist(),'angle_between_retained_and_reset_degrees':angle(q1+u2['p'],q1+ur['p']),'retained_norm':float(np.linalg.norm(q1+u2['p'])),'reset_norm':float(np.linalg.norm(q1+ur['p'])),'actual_Optax_moments':None,'actual_JAX_SPMD':None,'actual_checkpoint_restore':None,'actual_training_effect':None,'historical_execution_sha':None};(R/'analysis/adamh_probe.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print('AdamH original body / substitute helper checks:',len(checks),'angle',out['angle_between_retained_and_reset_degrees'])
