const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const R=path.resolve(__dirname,'..'),C=require('../assets/review-core.js'),f=JSON.parse(fs.readFileSync(path.join(R,'analysis/rubrics.json'))),d=JSON.parse(fs.readFileSync(path.join(R,'analysis/workbench_data.json')));let groups=0;
function check(label,fn){fn();groups++;}
check('Empty evidence cannot make a stage ready',()=>{const a=C.normalizeAudit({schema:'marin-review/1',target:'x',judgments:{}},f.rules);for(const id of f.pipeline[0].required)a.judgments[id]={status:'pass',evidence:''};assert.equal(C.evaluateStage(f.pipeline[0],a).ready,false);});
check('Unknown rules, incompatible versions and invalid status are rejected',()=>{assert.throws(()=>C.normalizeAudit({schema:'marin-review/1',target:'x',judgments:{R99:{status:'pass',evidence:'x'}}},f.rules));assert.throws(()=>C.normalizeAudit({schema:'marin-review/1',target:'x',judgments:{R01:{status:'perfect',evidence:'x'}}},f.rules));assert.throws(()=>C.normalizeAudit({schema:'marin-review/1',target:' ',judgments:{}},f.rules));assert.throws(()=>C.normalizeAudit({...f.example_audit,framework_version:'2.0'},f.rules));});
check('Partial and conflicting evidence stay visible',()=>{const a=C.normalizeAudit(f.example_audit,f.rules),s=f.pipeline[3];assert.equal(C.evaluateStage(s,a).ready,false);a.judgments.R07={status:'fail',evidence:'contradiction'};assert.deepEqual(C.evaluateStage(s,a).conflicts,['R07']);});
check('Not applicable needs a reason and cannot replace required evidence',()=>{assert.equal(C.effectiveStatus({status:'na',evidence:''}),'unassessed');assert.equal(C.effectiveStatus({status:'na',evidence:'static schedule, no order claim'}),'na');const a=C.normalizeAudit(f.example_audit,f.rules);a.judgments.R01={status:'na',evidence:'not relevant to my scope'};assert(!C.evaluateStage(f.pipeline[0],a).ready);});
check('Independent confirmation cannot be replaced by many unrelated passes',()=>{const a=C.normalizeAudit(f.example_audit,f.rules);for(const r of f.rules)a.judgments[r.id]={status:'pass',evidence:'declared reference'};a.judgments.R07={status:'unassessed',evidence:''};assert.equal(C.evaluateStage(f.pipeline[5],a).ready,false);});
check('Example is ready for observations, not actual capability or deployment',()=>{const a=C.normalizeAudit(f.example_audit,f.rules);assert(C.evaluateStage(f.pipeline[0],a).ready);assert(C.evaluateStage(f.pipeline[1],a).ready);assert(!C.evaluateStage(f.pipeline[3],a).ready);assert(!C.evaluateStage(f.pipeline[5],a).ready);});
check('Roundtrip preserves all judgments and Unicode notes',()=>{const a=C.normalizeAudit(f.example_audit,f.rules);a.judgments.R07.evidence='尚缺独立确认 <tag> & 原值';assert.deepEqual(C.normalizeAudit(JSON.parse(JSON.stringify(a)),f.rules),a);});
check('Changing baseline changes the observed math seed directions',()=>{const m=d.metrics.find(m=>m.key==='logprob_gsm8k_5shot'),old=C.compareMetric(m,'old'),p=C.compareMetric(m,'proportional');assert(old.points.every(x=>x.changePct>0));assert.equal(p.points.filter(x=>x.changePct>0).length,2);assert.equal(p.points.filter(x=>x.changePct<0).length,1);assert.throws(()=>C.compareMetric(m,'invented'));});
check('Mean marker is ratio of means, distinct from mean seed percentage',()=>{const m={means:{old:1.5,selected:1.6},seeds:[{seed:0,old:1,selected:1.2},{seed:1,old:1.5,selected:1.6},{seed:2,old:2,selected:2}]},x=C.compareMetric(m,'old');assert(Math.abs(x.meanChangePct-(1.6/1.5-1)*100)<1e-12);assert(Math.abs(x.meanChangePct-x.points.reduce((s,p)=>s+p.changePct,0)/3)>1);});
check('Explicit 1.0 migration retains other judgments and resets R16 without implicit acceptance',()=>{const old=JSON.parse(JSON.stringify(f.example_audit));old.framework_version='1.0';const before=JSON.stringify(old);assert.throws(()=>C.normalizeAudit(old,f.rules));const invalid=JSON.parse(JSON.stringify(old));invalid.judgments.R16.status='invented';assert.throws(()=>C.migrateAudit1_0(invalid,f.rules));const next=C.migrateAudit1_0(old,f.rules);assert.equal(next.framework_version,'1.1');assert.equal(next.judgments.R16.status,'unassessed');assert.deepEqual(JSON.parse(next.migration.prior_R16_json),old.judgments.R16);for(const id of Object.keys(old.judgments))if(id!=='R16')assert.deepEqual(next.judgments[id],old.judgments[id]);assert(!C.evaluateStage(f.pipeline[1],next).ready);assert.deepEqual(C.normalizeAudit(JSON.parse(JSON.stringify(next)),f.rules),next);assert.equal(JSON.stringify(old),before);});
check('Unversioned existing judgments cannot silently use changed anchors',()=>{const raw=JSON.parse(JSON.stringify(f.example_audit));delete raw.framework_version;assert.throws(()=>C.normalizeAudit(raw,f.rules));assert.equal(C.normalizeAudit({schema:'marin-review/1',target:'blank current version',judgments:{}},f.rules).framework_version,'1.1');});
const result={test_groups_passed:groups,scope:'Rubric input validation, claim-stage boundaries and baseline arithmetic; not external rubric validity or model training.'};fs.writeFileSync(path.join(R,'analysis/review_validation.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
