'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const R=path.resolve(__dirname,'..'),{analyze,quantize}=require(path.join(R,'assets/planner-core.js'));
const fixture=JSON.parse(fs.readFileSync(path.join(R,'analysis/planner_example.json'),'utf8'));
const clone=()=>JSON.parse(JSON.stringify(fixture)),near=(a,b,t=1e-10)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
let tests=0;const check=(name,f)=>{f();tests++;};
check('continuous budget and per-bucket exposure conservation',()=>{const r=analyze(clone());assert.equal(r.scheduleValid,true);near(r.continuousMatchedVsConstantL1B,0);near(r.rows.reduce((s,x)=>s+x.expectedB-x.historyB,0),100);near(r.rows[2].epochs,19/12);near(r.continuousSwappedVsMatchedL1B,40/3);});
check('integer allocations conserve every block',()=>{const r=analyze(clone());for(const q of Object.values(r.quantization))assert.equal(q.counts.reduce((s,x)=>s+x,0),49152);for(const xs of Object.values(r.effective))near(xs.reduce((s,x)=>s+x,0),1);});
check('infeasible aggregate capacity is reported',()=>{const x=clone();x.buckets.forEach(r=>r.capEpochs=0.1);const r=analyze(x);assert.equal(r.capacityFeasible,false);assert.ok(r.constraints.some(x=>x.includes('不足')));});
check('one bucket lower bound exceeds its capacity',()=>{const x=clone();x.buckets[2].capEpochs=.4;x.buckets[2].floorPct=10;const r=analyze(x);assert.ok(r.constraints.some(x=>x.includes('数学的保底')));});
check('historical exposure cannot be reset by planning',()=>{const x=clone();x.buckets[2].historyB=30;const r=analyze(x);assert.ok(r.constraints.some(x=>x.includes('历史曝光')));});
check('phase compensation can be out of simplex',()=>{const x=clone();x.buckets[2].earlyShiftPP=15;x.buckets[0].earlyShiftPP=-15;assert.equal(analyze(x).scheduleValid,false);});
check('invalid or nonfinite input rejected',()=>{for(const mutate of [x=>x.budgetB=NaN,x=>x.blockUnits=1.5,x=>x.buckets[0].stockB=0,x=>x.buckets[0].weightPct=-1,x=>x.buckets[0].earlyShiftPP=1,x=>x.buckets[0].name=x.buckets[1].name]){const x=clone();mutate(x);assert.throws(()=>analyze(x));}});
check('positive weight can disappear under integer sampling',()=>{const q=quantize([.99999,.00001],10);assert.deepEqual(q.counts,[10,0]);assert.deepEqual(q.zero,[1]);});
check('largest bucket receives residual including tie rule',()=>{const q=quantize([.4,.4,.2],7);assert.deepEqual(q.counts,[4,2,1]);assert.equal(q.remainder,2);assert.equal(q.recipient,0);});
check('matched rounded schedule is checked against caps',()=>{const x=clone();x.blockUnits=7;x.buckets[0].capEpochs=(20+45)/120;const r=analyze(x);assert.ok(r.rows[0].violations.some(x=>x.includes('取整后的计划曝光')));});
check('equal stage lengths make literal swapping exposure-neutral',()=>{const x=clone();x.earlyFraction=.5;near(analyze(x).continuousSwappedVsMatchedL1B,0);});
check('random feasible schedules preserve continuous exposure',()=>{let state=8435;const rand=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/2**32;};for(let i=0;i<100;i++){const x=clone();x.earlyFraction=.2+.6*rand();const d=rand()*2;x.buckets[0].earlyShiftPP=-d;x.buckets[2].earlyShiftPP=d;const r=analyze(x);assert.ok(r.scheduleValid);near(r.continuousMatchedVsConstantL1B,0,1e-8);}});
const out={test_groups_passed:tests,random_schedule_cases:100,claims_verified:['budget conservation','balanced phase compensation','unequal-stage swapping changes exposure','aggregate and per-bucket infeasibility','history retention','floor and epoch limits after quantization','zero-count buckets','finite and normalized inputs'],scope:'Arithmetic tests; no model training or Loss prediction.'};
fs.writeFileSync(path.join(R,'analysis/planner_validation.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));
