const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const R=path.resolve(__dirname,'..'),C=require('../assets/assessment-core.js'),bank=JSON.parse(fs.readFileSync(path.join(R,'analysis/assessment_data.json'))),replay=JSON.parse(fs.readFileSync(path.join(R,'analysis/assessment_authored_replays.json'))),tests=[];
const clone=x=>JSON.parse(JSON.stringify(x)),time='2026-10-05T00:00:00.000Z';
const review=(label,ratings={scope:2,mechanism:2,next:2},errors=[])=>({reviewer_label:label,ratings,critical_status:errors.length?'issues':'none',critical_errors:errors,evidence_note:'作者例中的原句与题库锚点对应；此处只是记录逻辑测试。',saved_at:time});
function answer(id='Q01'){const r=C.blank(bank);r.cases[id].draft='用于结构测试的回答，不是真实读者观察。';return C.addAnswer(r,bank,id,time);}
function grade(r,id,slot,v){return C.putReview(r,bank,id,id+'-r1',slot,v);}
function check(label,fn){fn();tests.push(label);}
check('Blank or unattempted cases stay unknown rather than zero or pass',()=>{const r=C.blank(bank);assert(C.summary(r,bank).cases.every(c=>!c.answered&&c.anchor_status==='not_assessed'));assert.throws(()=>C.addAnswer(r,bank,'Q01',time));});
check('Thirty authored annotations replay without becoming external observations',()=>{assert.equal(replay.examples.length,30);for(const e of replay.examples){let r=C.blank(bank);r.cases[e.case_id].draft=e.authored_answer;r=C.addAnswer(r,bank,e.case_id,time);for(const slot of ['A','B'])r=grade(r,e.case_id,slot,review(slot,e.author_assigned_ratings,e.author_assigned_critical_errors));const s=C.summary(r,bank),c=s.cases.find(c=>c.case_id===e.case_id);assert.equal(c.anchor_status,e.kind==='bounded'?'local_anchors_met':e.kind==='generic'?'needs_revision':'critical_overreach');assert.equal(s.external_reader_study,null);assert.equal(s.training_gate_decision,null);assert.equal(c.external_comprehension_verified,false);}});
check('Critical overreach cannot be averaged away by all other perfect ratings',()=>{let r=answer();for(const slot of ['A','B'])r=grade(r,'Q01',slot,review(slot,undefined,['Q01-E1']));assert.equal(C.summary(r,bank).cases[0].anchor_status,'critical_overreach');assert.equal(C.summary(r,bank).overall_score,null);});
check('Unknown dimensions, critical checks and absent evidence cannot settle a review',()=>{let r=answer();const v=review('A');v.critical_status='not_checked';r=grade(r,'Q01','A',v);r=grade(r,'Q01','B',review('B'));assert.equal(C.summary(r,bank).cases[0].review_status,'reviews_pending');const missing=review('A');missing.evidence_note='';assert(!C.complete(missing));const ungraded=review('A');ungraded.ratings.next=null;assert(!C.complete(ungraded));});
check('Versions, source hashes and undeclared cases are rejected before mutation',()=>{const r=answer(),before=JSON.stringify(r);for(const change of [x=>x.protocol_version='9',x=>x.bank_sha256='bad',x=>x.cases.Q99={},x=>x.cases.Q01.revisions[0].reviews.X=null]){const bad=clone(r);change(bad);assert.throws(()=>C.normalize(bad,bank));}assert.equal(JSON.stringify(r),before);});
check('Answer revisions preserve prior text and review rather than inheriting pass',()=>{let r=answer();r=grade(r,'Q01','A',review('A'));r=grade(r,'Q01','B',review('B'));r=C.openReference(r,bank,'Q01','2026-10-05T00:01:00Z');r.cases.Q01.draft='读完后的修订，不是迁移表现。';r=C.addAnswer(r,bank,'Q01','2026-10-05T00:02:00Z');assert.equal(r.cases.Q01.revisions[0].reference_in_page_status,'not_opened_in_this_page');assert.equal(r.cases.Q01.revisions[1].reference_in_page_status,'opened_before_save');assert.equal(C.summary(r,bank).cases[0].review_status,'reviews_pending');assert.equal(r.cases.Q01.revisions[0].review_events.length,2);assert.equal(C.summary(r,bank).same_question_revision_is_transfer_evidence,false);});
check('Reviewer disagreement keeps two original ratings and is never averaged',()=>{let r=answer();r=grade(r,'Q01','A',review('A'));r=grade(r,'Q01','B',review('B',{scope:2,mechanism:1,next:2}));const s=C.summary(r,bank).cases[0];assert(s.disagreement_open);assert.equal(s.anchor_status,'not_settled');assert.equal(r.cases.Q01.revisions[0].reviews.B.ratings.mechanism,1);});
check('Identical reviewer labels cannot masquerade as distinct review',()=>{let r=answer();for(const slot of ['A','B'])r=grade(r,'Q01',slot,review('same'));const s=C.summary(r,bank).cases[0];assert.equal(s.review_status,'same_reviewer_label');assert(!s.claimed_distinct_reviewers);assert.equal(s.anchor_status,'not_settled');});
check('Adjudication requires a real recorded disagreement and preserves the original basis',()=>{let r=answer();assert.throws(()=>grade(r,'Q01','adjudication',review('C')));r=grade(r,'Q01','A',review('A'));r=grade(r,'Q01','B',review('B',{scope:1,mechanism:2,next:2}));assert.throws(()=>grade(r,'Q01','adjudication',review('A')));r=grade(r,'Q01','adjudication',review('C'));assert.equal(C.summary(r,bank).cases[0].review_status,'manually_adjudicated');assert.equal(r.cases.Q01.revisions[0].reviews.B.ratings.scope,1);assert.throws(()=>grade(r,'Q01','B',review('B')));});
check('Revised reviewer opinions retain earlier events and inconsistent history is rejected',()=>{let r=answer();r=grade(r,'Q01','A',review('A',{scope:1,mechanism:0,next:0}));r=grade(r,'Q01','A',review('A'));assert.equal(r.cases.Q01.revisions[0].review_events.length,2);assert.equal(r.cases.Q01.revisions[0].review_events[0].review.ratings.scope,1);const bad=clone(r);bad.cases.Q01.revisions[0].reviews.A.ratings.scope=0;assert.throws(()=>C.normalize(bad,bank));});
check('Fabricated imported summary claims cannot grant comprehension or training decisions',()=>{let r=answer();r.summary={overall_score:100,external_reader_study:'validated',training_gate_decision:'pass'};const out=C.exportRecord(r,bank);assert.equal(out.summary.overall_score,null);assert.equal(out.summary.training_gate_decision,null);assert.equal(out.summary.external_reader_study,null);});
check('Unicode and HTML-like answer text survive JSON while fixed fields stay bounded',()=>{let r=C.blank(bank);r.cases.Q01.draft='<img src=x onerror="alert(1)"> 中文 & 范围';r=C.addAnswer(r,bank,'Q01',time);assert.deepEqual(C.normalize(JSON.parse(JSON.stringify(r)),bank),r);const bad=clone(r);bad.cases.Q01.draft='x'.repeat(12001);assert.throws(()=>C.normalize(bad,bank));});
check('Contradictory critical status or invalid scores fail without changing the original',()=>{const r=answer(),before=JSON.stringify(r);for(const f of [x=>x.critical_errors=['Q01-E1'],x=>x.ratings.scope=3,x=>x.ratings.next=true,x=>x.critical_errors=['Q99-E1']]){const v=review('A');f(v);assert.throws(()=>grade(r,'Q01','A',v));}assert.equal(JSON.stringify(r),before);});
const result={test_groups_passed:tests.length,tests,authored_replay_count:30,scope:'Manual assessment state, revision and provenance boundaries; no automatic Chinese grading, external reader result or scoring validity verified'};fs.writeFileSync(path.join(R,'analysis/assessment_validation.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
