"""V121 source provenance, numerical conservation, archived tables and HTML scope."""
import pathlib,json,hashlib,csv,subprocess
from bs4 import BeautifulSoup
R=pathlib.Path(__file__).resolve().parents[1];checks=[]
def ok(n,v):assert v,n;checks.append({'name':n,'passed':True})
old=BeautifulSoup(subprocess.check_output(['git','show','report-v120-2026-10-08:index.html'],cwd=R),'html.parser');now=BeautifulSoup((R/'index.html').read_text(),'html.parser');stand=BeautifulSoup((R/'report_standalone.html').read_text(),'html.parser')
ok('Historical prose prefixes and all prior section tables retained',all((R/p).read_bytes().startswith(subprocess.check_output(['git','show','report-v120-2026-10-08:'+p],cwd=R)) for p in ['BATCH_CLOCK_ZH.md','PRACTICAL_ZH.md','DATA_GUIDE_ZH.md','MIXTURE_IDENTITY_ZH.md','SYNTHESIS_ZH.md','RUBRICS_ZH.md','PIPELINE_ZH.md','IMPROVEMENT_LOG_ZH.md','DELIVERY_AUDIT_ZH.md']) and all(now.select_one('#'+x['id']) and [t.get_text(' ',strip=True) for t in x.select('table')]==[t.get_text(' ',strip=True) for t in now.select_one('#'+x['id']).select('table')][:len(x.select('table'))] for x in old.select('section[id]') if x.select('table')))
prior=json.loads(subprocess.check_output(['git','show','report-v120-2026-10-08:sources/archive_manifest.json'],cwd=R));records=json.loads((R/'sources/source_manifest.json').read_text());prevrecords=json.loads(subprocess.check_output(['git','show','report-v120-2026-10-08:sources/source_manifest.json'],cwd=R))
ok('572 prior non-bookkeeping sources unchanged and one acquisition appended',len(prior['files'])==573 and all(hashlib.sha256((R/'sources'/x['file']).read_bytes()).hexdigest()==x['sha256'] for x in prior['files'] if x['file']!='source_manifest.json') and records[:-1]==prevrecords and records[-1]['file']=='resume_boundary_2026_10_08/producer_meta.json')
j=json.loads((R/'analysis/ablation_resume_boundary.json').read_text());a=json.loads((R/'analysis/resume_boundary_acquisition_v121.json').read_text());raw=json.loads((R/'sources'/a['records'][0]['file']).read_text())['data']['project']['run'];cfg=json.loads(raw['config']);summary=json.loads(raw['summaryMetrics'])
ok('Public producer request and response bind phase declarations and nominal progress',a['records'][0]['request']['variables']['r']==raw['name'] and a['records'][0]['sha256']==hashlib.sha256((R/'sources'/a['records'][0]['file']).read_bytes()).hexdigest() and [s for s,w in cfg['data']['value']['train_weights']]==[0,3120] and summary['_step']==392 and summary['throughput/total_tokens']==393*1024*4096)
cells=list(csv.DictReader((R/'analysis/ablation_resume_boundary_cells.csv').open()));groups={}
for r in cells:groups.setdefault((r['group'],r['domain']),[]).append(r)
ok('Twelve bound source controls and 16000 per-cell records conserve prefix slots',j['checks_passed']==12 and all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in j['source_sha256'].items()) and len(cells)==16000 and len(groups)==80 and all(sum(int(r['producer_block_prefix_count']) for r in rs)==sum(int(r['declared_block_prefix_count']) for r in rs)==9216 and all(int(r['declared_minus_producer'])==int(r['declared_block_prefix_count'])-int(r['producer_block_prefix_count']) for r in rs) for rs in groups.values()))
f=json.loads((R/'analysis/ablation_resume_boundary_figure.json').read_text())
ok('Both HTML variants expose declared timeline and preserve historical repetition uncertainty',all(s.select_one('#batch-clock-guide #ablation-resume-title') and all(t in s.select_one('#batch-clock-guide').get_text() for t in ['V121','9216','5129','未执行','实际checkpoint']) for s in [now,stand]) and f['analysis_sha256']==hashlib.sha256((R/'analysis/ablation_resume_boundary.json').read_bytes()).hexdigest() and f['figure_sha256']==hashlib.sha256((R/'assets/ablation_resume_boundary.svg').read_bytes()).hexdigest() and all(j[k] is None for k in ['actual_checkpoint_contents_verified','actual_historical_mixture_key','actual_token_repetition_count','actual_training_loss_effect','actual_production_incident','actual_bridge_training_result']))
(R/'analysis/static_validation_v121.json').write_text(json.dumps({'checks_passed':len(checks),'checks':checks,'actual_browser_rendering':None},indent=2)+'\n');print('Static checks',len(checks))
