"""V123 archive preservation, independent key arithmetic, exact rows and reading scope."""
import csv,hashlib,json,pathlib,subprocess
from bs4 import BeautifulSoup
R=pathlib.Path(__file__).resolve().parents[1];A=R/'analysis';checks=[]
def ok(n,v):assert v,n;checks.append({'name':n,'passed':True})
prior=json.loads(subprocess.check_output(['git','show','report-v122-2026-10-08:sources/archive_manifest.json'],cwd=R));rec=json.loads((R/'sources/source_manifest.json').read_text());prev=json.loads(subprocess.check_output(['git','show','report-v122-2026-10-08:sources/source_manifest.json'],cwd=R))
ok('584 prior non-bookkeeping sources preserved and eight acquisition records appended',len(prior['files'])==585 and rec[:-8]==prev and all(x['file'].startswith('historical_key_2026_10_08/') and hashlib.sha256((R/'sources'/x['file']).read_bytes()).hexdigest()==x['sha256'] for x in rec[-8:]) and all(hashlib.sha256((R/'sources'/x['file']).read_bytes()).hexdigest()==x['sha256'] for x in prior['files'] if x['file']!='source_manifest.json'))
j=json.loads((A/'historical_key_versions.json').read_text());n=json.loads((A/'historical_key_pipeline_jax_0_11_0.json').read_text());o=json.loads((A/'historical_key_pipeline_jax_0_7_2.json').read_text())
ok('Five cross-runtime and both nine-control results bind archived sources and current probes',j['checks_passed']==5 and n['checks_passed']==o['checks_passed']==9 and all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for d in [j,n,o] for p,h in d['source_sha256'].items()) and len(j['bindings'])==6 and all(x['matches_both_run_manifests'] for x in j['bindings']))
a=n['variants']['partitionable=True,seed=0,data_seed=None'];b=n['variants']['partitionable=True,seed=0,data_seed=0'];c=n['variants']['partitionable=True,seed=1,data_seed=0'];off=n['variants']['partitionable=False,seed=0,data_seed=None'];rows=list(csv.DictReader((A/'historical_child_keys_jax_0_11_0.csv').open()));rowgroups={}
for r in rows:rowgroups.setdefault(r['variant'],{})[r['cell']]=[int(r['key0']),int(r['key1'])]
ok('Independent key records verifyNone-zero semantics, fixed data seed and flag changes',len(rows)==1600 and len(rowgroups)==8 and all(rowgroups[k]==v['child_keys'] for k,v in n['variants'].items()) and a['model_key']==b['model_key'] and a['data_key']!=b['data_key'] and b['data_key']==c['data_key'] and b['child_keys']==c['child_keys'] and b['model_key']!=c['model_key'] and sum(a['child_keys'][k]!=b['child_keys'][k] for k in a['child_keys'])==sum(a['child_keys'][k]!=off['child_keys'][k] for k in a['child_keys'])==200 and n['variants']==o['variants'])
ok('Runtime comparison and boundary counts preserve all historical execution unknowns',n['boundary_with_declared_derived_key']==o['boundary_with_declared_derived_key'] and n['boundary_with_declared_derived_key']['hybrid_block_repeated_logical_ids']==5346 and all(j[k] is None for k in ['actual_executed_historical_key','actual_runtime_imports_verified','actual_token_repetition_count','actual_training_loss_effect','actual_model_seed_variance_isolated']) and json.loads((R/'templates/random_stream_review.json').read_text())['status']=='proposed_not_executed')
old=BeautifulSoup(subprocess.check_output(['git','show','report-v122-2026-10-08:index.html'],cwd=R),'html.parser');now=BeautifulSoup((R/'index.html').read_text(),'html.parser');stand=BeautifulSoup((R/'report_standalone.html').read_text(),'html.parser')
ok('Prior prose and tables retained, both HTML variants distinguish initialization from restore',all((R/p).read_bytes().startswith(subprocess.check_output(['git','show','report-v122-2026-10-08:'+p],cwd=R)) for p in ['RUN_CODE_PROVENANCE_ZH.md','BATCH_CLOCK_ZH.md','RUBRICS_ZH.md','PIPELINE_ZH.md','IMPROVEMENT_LOG_ZH.md','DELIVERY_AUDIT_ZH.md']) and all([t.get_text(' ',strip=True) for t in x.select('table')]==[t.get_text(' ',strip=True) for t in now.select_one('#'+x['id']).select('table')][:len(x.select('table'))] for x in old.select('section[id]') if x.select('table')) and all(s.select_one('#run-code-guide #historical-key-title') and s.select_one('#run-code-guide #run-code-evidence-title') and all(t in s.select_one('#run-code-guide').get_text() for t in ['V123','5346','7938','初始化key改变不证明续训模型参数改变','没有出现在已核查源码中']) for s in [now,stand]))
(A/'static_validation_v123.json').write_text(json.dumps({'checks_passed':len(checks),'checks':checks,'actual_browser_rendering':None},indent=2)+'\n');print('Static checks',len(checks))
