"""V125 archive preservation, independent IO-index aggregation and explicit reference scope."""
import pathlib,json,hashlib,subprocess,collections,math
from bs4 import BeautifulSoup
R=pathlib.Path(__file__).resolve().parents[1];A=R/'analysis';checks=[]
def ok(n,v):assert v,n;checks.append({'name':n,'passed':True})
prior=json.loads(subprocess.check_output(['git','show','report-v124-2026-10-08:sources/archive_manifest.json'],cwd=R))
ok('All595prior source payloads and acquisition/archive bookkeeping unchanged',len(prior['files'])==595 and all(hashlib.sha256((R/'sources'/x['file']).read_bytes()).hexdigest()==x['sha256'] for x in prior['files']) and (R/'sources/archive_manifest.json').read_bytes()==subprocess.check_output(['git','show','report-v124-2026-10-08:sources/archive_manifest.json'],cwd=R))
j=json.loads((A/'prefix_sampling_structure.json').read_text());old=json.loads((A/'simulated_inventory_cpu.json').read_text());verified=[]
for row in j['four_prefixes']:
 ids=[int(x.split(':')[1]) for x in old['cases'][row['case']]['pools'][row['cell']]];h=collections.Counter(i//256 for i in ids);verified.append(len(h)==row['distinct_io_blocks'] and sum(v*(v-1)//2 for v in h.values())==row['same_io_block_pairs'] and row['unique_sequences']==len(set(ids))==879 and set(h).issubset(set(row['layout_full_blocks'])) and len(row['layout_full_blocks'])==512)
ok('Four independently regrouped879identity prefixes obey recorded512-block cap',len(verified)==4 and all(verified) and j['checks_passed']==9 and all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in j['source_sha256'].items()))
n=1000000;k=879;b=256;full,tail=divmod(n,b);pair=k*(k-1)/2*(full*b*(b-1)+tail*(tail-1))/(n*(n-1));counter=[256*i for i in range(879)];support=j['structural_support_counterexample']
ok('Exact support counterexample and independent pair expectation match without inference to quality',max(counter)<n and len(set(counter))==879 and len({i//256 for i in counter})==879>512 and support['loader_prefix_probability_under_contract']==0 and abs(pair-j['uniform_without_replacement_reference']['expected_same_io_block_pairs'])<1e-12 and j['tiny_exact_enumeration']['combinations']==120 and len(j['tail_boundary_controls'])==24 and all(t['prefix_tail_hits']==0 for t in j['tail_boundary_controls']))
f=json.loads((A/'prefix_sampling_figure.json').read_text());ok('Scientific points and theoretical reference bound with all production effects unknown',f['observed_prefix_distinct_blocks']==[r['distinct_io_blocks'] for r in j['four_prefixes']] and f['window_distinct_blocks']==[4,64,442,873] and f['analysis_sha256']==hashlib.sha256((A/'prefix_sampling_structure.json').read_bytes()).hexdigest() and f['figure_sha256']==hashlib.sha256((R/'assets/prefix_sampling_structure.svg').read_bytes()).hexdigest() and f['png_sha256']==hashlib.sha256((R/'assets/prefix_sampling_structure.png').read_bytes()).hexdigest() and all(j[k] is None for k in ['actual_Hero_prefix_representativeness','actual_tail_sequence_contents','actual_domain_quality_bias','actual_performance_effect','actual_training_loss_effect']))
prev=BeautifulSoup(subprocess.check_output(['git','show','report-v124-2026-10-08:index.html'],cwd=R),'html.parser');now=BeautifulSoup((R/'index.html').read_text(),'html.parser');stand=BeautifulSoup((R/'report_standalone.html').read_text(),'html.parser')
ok('Prior prose/tables retained and both HTML variants distinguish sampling geometry from quality',all((R/p).read_bytes().startswith(subprocess.check_output(['git','show','report-v124-2026-10-08:'+p],cwd=R)) for p in ['RUN_CODE_PROVENANCE_ZH.md','DATA_GUIDE_ZH.md','MIXTURE_IDENTITY_ZH.md','RUBRICS_ZH.md','PIPELINE_ZH.md','SYNTHESIS_ZH.md','IMPROVEMENT_LOG_ZH.md','DELIVERY_AUDIT_ZH.md']) and all([t.get_text(' ',strip=True) for t in x.select('table')]==[t.get_text(' ',strip=True) for t in now.select_one('#'+x['id']).select('table')][:len(x.select('table'))] for x in prev.select('section[id]') if x.select('table')) and all(s.select_one('#run-code-guide #prefix-sampling-title') and all(t in s.select_one('#run-code-guide').get_text() for t in ['V125','787.52','873比442多','不需要拿四个key做显著性检验','当前没有证据表明真实桶接近这个边界']) for s in [now,stand]) and json.loads((R/'templates/prefix_sampling_review.json').read_text())['status']=='proposed_not_executed')
(A/'static_validation_v125.json').write_text(json.dumps({'checks_passed':len(checks),'checks':checks,'actual_browser_rendering':None},indent=2)+'\n');print('Static checks',len(checks))
