"""V124 independent finite-pool arithmetic, source preservation and HTML scope checks."""
import pathlib,json,hashlib,subprocess,collections
from bs4 import BeautifulSoup
R=pathlib.Path(__file__).resolve().parents[1];A=R/'analysis';checks=[]
def ok(n,v):assert v,n;checks.append({'name':n,'passed':True})
p=json.loads(subprocess.check_output(['git','show','report-v123-2026-10-08:sources/archive_manifest.json'],cwd=R));rec=json.loads((R/'sources/source_manifest.json').read_text());prev=json.loads(subprocess.check_output(['git','show','report-v123-2026-10-08:sources/source_manifest.json'],cwd=R))
ok('592 prior non-bookkeeping source payloads unchanged and two acquisition records appended',len(p['files'])==593 and rec[:-2]==prev and all(x['file'].startswith('simulated_inventory_2026_10_08/') for x in rec[-2:]) and all(hashlib.sha256((R/'sources'/x['file']).read_bytes()).hexdigest()==x['sha256'] for x in p['files'] if x['file']!='source_manifest.json'))
j=json.loads((A/'simulated_inventory_cpu.json').read_text());cases=j['cases'];names=['c00q0','c00q1'];contrasts={s:{n:{'intersection':len(set(cases[s+'_default']['pools'][n])&set(cases[s+'_zero']['pools'][n])),'symmetric_difference':len(set(cases[s+'_default']['pools'][n])^set(cases[s+'_zero']['pools'][n]))} for n in names} for s in ['full','half','realratio']}
ok('All independently counted finite-pool intersections and lengths agree',contrasts==j['pool_contrasts'] and all(len(set(v['pools'][n]))==v['selected_lengths'][n] for v in cases.values() for n in names) and j['checks_passed']==9 and all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in j['source_sha256'].items()))
h=j['mixed_restart_histograms'];ok('Independent exposure totals and zero-length arithmetic preserve source threshold',all(set(h[g][n])==set(cases['half_default']['pools'][n]) for g in h for n in names) and [sum(h['equal'][n].values()) for n in names]==[256,256] and [sum(h['redistributed'][n].values()) for n in names]==[128,384] and int(1137*j['declared_simulation_ratio'])==0 and int(1138*j['declared_simulation_ratio'])==1 and j['empty_inventory_control']['first_nonempty_full_sequences']==1138)
f=json.loads((A/'simulated_inventory_figure.json').read_text());ok('Diagram bound to artificial data and all production implications remain unknown',f['analysis_sha256']==hashlib.sha256((A/'simulated_inventory_cpu.json').read_bytes()).hexdigest() and f['figure_sha256']==hashlib.sha256((R/'assets/simulated_inventory.svg').read_bytes()).hexdigest() and all(j[k] is None for k in ['actual_training_pool_membership_verified','actual_production_zero_length_cell','actual_checkpoint_contents_verified','actual_token_repetition_count','actual_training_loss_effect']) and json.loads((R/'templates/simulated_inventory_review.json').read_text())['status']=='proposed_not_executed')
old=BeautifulSoup(subprocess.check_output(['git','show','report-v123-2026-10-08:index.html'],cwd=R),'html.parser');now=BeautifulSoup((R/'index.html').read_text(),'html.parser');stand=BeautifulSoup((R/'report_standalone.html').read_text(),'html.parser')
ok('Historical prose/table prefixes preserved and both HTML variants retain causal limits',all((R/p).read_bytes().startswith(subprocess.check_output(['git','show','report-v123-2026-10-08:'+p],cwd=R)) for p in ['RUN_CODE_PROVENANCE_ZH.md','DATA_GUIDE_ZH.md','RUBRICS_ZH.md','PIPELINE_ZH.md','SYNTHESIS_ZH.md','IMPROVEMENT_LOG_ZH.md','DELIVERY_AUDIT_ZH.md']) and all([t.get_text(' ',strip=True) for t in x.select('table')]==[t.get_text(' ',strip=True) for t in now.select_one('#'+x['id']).select('table')][:len(x.select('table'))] for x in old.select('section[id]') if x.select('table')) and all(s.select_one('#run-code-guide #sim-inventory-title') and all(t in s.select_one('#run-code-guide').get_text() for t in ['V124','1137','1138','879','没有证据表明这次生产或搜索真实出现了空桶','不是整个历史checkpoint文件内容的完整审计']) for s in [now,stand]))
(A/'static_validation_v124.json').write_text(json.dumps({'checks_passed':len(checks),'checks':checks,'actual_browser_rendering':None},indent=2)+'\n');print('Static checks',len(checks))
