"""V120 independent raw-registry recomputation, source integrity and publication scope."""
import pathlib,json,hashlib,csv,subprocess
import pyarrow.parquet as pq
from bs4 import BeautifulSoup
R=pathlib.Path(__file__).resolve().parents[1];checks=[]
def ok(n,v):assert v,n;checks.append({'name':n,'passed':True})
old=BeautifulSoup(subprocess.check_output(['git','show','report-v119-2026-10-08:index.html'],cwd=R),'html.parser');now=BeautifulSoup((R/'index.html').read_text(),'html.parser');stand=BeautifulSoup((R/'report_standalone.html').read_text(),'html.parser')
ok('Historical appended prose and all previous section tables retained',all((R/p).read_bytes().startswith(subprocess.check_output(['git','show','report-v119-2026-10-08:'+p],cwd=R)) for p in ['PRACTICAL_ZH.md','DATA_GUIDE_ZH.md','MIXTURE_IDENTITY_ZH.md','SYNTHESIS_ZH.md','RUBRICS_ZH.md','PIPELINE_ZH.md','IMPROVEMENT_LOG_ZH.md','DELIVERY_AUDIT_ZH.md']) and all(now.select_one('#'+x['id']) and [t.get_text(' ',strip=True) for t in x.select('table')]==[t.get_text(' ',strip=True) for t in now.select_one('#'+x['id']).select('table')][:len(x.select('table'))] for x in old.select('section[id]') if x.select('table')))
prior=json.loads(subprocess.check_output(['git','show','report-v119-2026-10-08:sources/archive_manifest.json'],cwd=R))
ok('All 573 archived source files byte preserved',len(prior['files'])==573 and all(hashlib.sha256((R/'sources'/x['file']).read_bytes()).hexdigest()==x['sha256'] for x in prior['files']))
raw_path=R/'sources/deepening_2026_10_04/hf_observations.parquet';raw={r['run_name']:r for r in pq.read_table(raw_path).to_pylist()};responses=list(csv.DictReader((R/'analysis/ablation_context_responses.csv').open()))
ok('4320 response contrasts independently recomputed from pinned raw registry',len(responses)==4320 and all(float(r['baseline_bpb'])==raw[r['control_run']]['grouped_bpb'][r['metric']] and float(r['ablation_bpb'])==raw[r['run_name']]['grouped_bpb'][r['metric']] and abs(float(r['relative_change_pct'])-100*(raw[r['run_name']]['grouped_bpb'][r['metric']]-raw[r['control_run']]['grouped_bpb'][r['metric']])/raw[r['control_run']]['grouped_bpb'][r['metric']])<1e-12 for r in responses))
j=json.loads((R/'analysis/ablation_context.json').read_text());keys=list(csv.DictReader((R/'analysis/ablation_child_key_replay.csv').open()))
ok('Eleven controls bind configs and original methods with complete history and unchanged recorded keys',j['checks_passed']==11 and len(keys)==16000 and all(r['key_changed']=='False' and r['baseline_key']==r['ablation_key'] for r in keys) and all(r['recorded_stage_starts']==[0,384,3120] for r in j['conditional_key_replays']) and all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in j['source_sha256'].items()))
f=json.loads((R/'analysis/ablation_context_figure.json').read_text())
ok('Both HTML variants expose all-point response plot and unknown historical/causal effects',all(s.select_one('#practical #ablation-context-title') and all(t in s.select_one('#practical').get_text() for t in ['V120','31','反事实','没有新训练','573']) for s in [now,stand]) and len(f['panels'])==3 and all(p['domain_points']==40 and all(p['axis_limits'][0]<=v<=p['axis_limits'][1] for xy in p['points'] for v in xy) for p in f['panels']) and f['analysis_sha256']==hashlib.sha256((R/'analysis/ablation_context.json').read_bytes()).hexdigest() and f['figure_sha256']==hashlib.sha256((R/'assets/ablation_context.svg').read_bytes()).hexdigest() and all(j[k] is None for k in ['actual_historical_child_keys','actual_token_stream_difference','actual_key_reassignment_loss_effect','actual_independent_training_confirmation','actual_535B_transfer_effect']))
(R/'analysis/static_validation_v120.json').write_text(json.dumps({'checks_passed':len(checks),'checks':checks,'raw_registry_sha256':hashlib.sha256(raw_path.read_bytes()).hexdigest(),'actual_browser_rendering':None},indent=2)+'\n');print('Static checks',len(checks))
