"""V122 independent archive bindings, replay comparison, scope and HTML preservation."""
import pathlib,json,hashlib,base64,subprocess,csv
from bs4 import BeautifulSoup
R=pathlib.Path(__file__).resolve().parents[1];D=R/'sources/run_code_2026_10_08';checks=[]
def ok(n,v):assert v,n;checks.append({'name':n,'passed':True})
prior=json.loads(subprocess.check_output(['git','show','report-v121-2026-10-08:sources/archive_manifest.json'],cwd=R));records=json.loads((R/'sources/source_manifest.json').read_text());prev=json.loads(subprocess.check_output(['git','show','report-v121-2026-10-08:sources/source_manifest.json'],cwd=R))
ok('573 prior non-bookkeeping sources preserved and eleven acquisition records appended',len(prior['files'])==574 and all(hashlib.sha256((R/'sources'/x['file']).read_bytes()).hexdigest()==x['sha256'] for x in prior['files'] if x['file']!='source_manifest.json') and records[:-11]==prev and len(records[-11:])==11 and all(x['file'].startswith('run_code_2026_10_08/') and hashlib.sha256((R/'sources'/x['file']).read_bytes()).hexdigest()==x['sha256'] for x in records[-11:]))
a=json.loads((R/'analysis/run_code_provenance.json').read_text());manifests={r:json.loads((D/(r+'_code_manifest.json')).read_text())['contents'] for r in ['producer','continuation']}
ok('Independent five-file content digests match both public code manifests',len(a['file_bindings'])==5 and all(all(base64.b64encode(hashlib.md5((R/b['local_file']).read_bytes()).digest()).decode()==m[b['artifact_path']]['digest'] and (R/b['local_file']).stat().st_size==m[b['artifact_path']]['size'] for m in manifests.values()) for b in a['file_bindings']) and all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in a['source_sha256'].items()))
ok('Every saved restore-log line is verbatim and uncertainty remains explicit',len(a['log_evidence'])>=4 and all((R/x['file']).read_text().splitlines()[x['line']-1]==x['text'] for x in a['log_evidence']) and all(a[k] is None for k in ['actual_runtime_imports_verified','actual_checkpoint_contents_verified','actual_historical_mixture_key','actual_token_repetition_count','actual_training_loss_effect','all_eighty_artifacts_verified']))
old=json.loads((R/'analysis/ablation_resume_boundary.json').read_text());new=json.loads((R/'analysis/historical_ablation_resume_boundary.json').read_text());oc=list(csv.DictReader((R/'analysis/ablation_resume_boundary_cells.csv').open()));nc=list(csv.DictReader((R/'analysis/historical_ablation_resume_boundary_cells.csv').open()))
ok('All historical-source replay cases and sixteen-thousand cell rows preserve prior values',new['checks_passed']==12 and a['checks_passed']==8 and len(old['cases'])==len(new['cases'])==80 and old['cases']==new['cases'] and len(oc)==len(nc)==16000 and oc==nc)
priorhtml=BeautifulSoup(subprocess.check_output(['git','show','report-v121-2026-10-08:index.html'],cwd=R),'html.parser');now=BeautifulSoup((R/'index.html').read_text(),'html.parser');stand=BeautifulSoup((R/'report_standalone.html').read_text(),'html.parser')
ok('Prior prose and table prefixes preserved, both HTML variants expose scoped evidence diagram',all((R/p).read_bytes().startswith(subprocess.check_output(['git','show','report-v121-2026-10-08:'+p],cwd=R)) for p in ['BATCH_CLOCK_ZH.md','PRACTICAL_ZH.md','RUBRICS_ZH.md','PIPELINE_ZH.md','IMPROVEMENT_LOG_ZH.md','DELIVERY_AUDIT_ZH.md']) and all([t.get_text(' ',strip=True) for t in x.select('table')]==[t.get_text(' ',strip=True) for t in now.select_one('#'+x['id']).select('table')][:len(x.select('table'))] for x in priorhtml.select('section[id]') if x.select('table')) and all(s.select_one('#run-code-guide #run-code-evidence-title') and len(s.select('#run-code-guide table'))==1 and all(t in s.select_one('#run-code-guide').get_text() for t in ['null','29,890','29,896','未确认','不是实际重复 token']) for s in [now,stand]))
(R/'analysis/static_validation_v122.json').write_text(json.dumps({'checks_passed':len(checks),'checks':checks,'actual_browser_rendering':None},indent=2)+'\n');print('Static checks',len(checks))
